services:
  db:
    image: docker.io/library/mariadb:12.1.2-ubi
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./volumes/db:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  moodle:
    build:
      context: ./moodle
    image: moodle-php8.3-apache-trixie
    pull_policy: never
    environment:
      - MOODLE_DB_TYPE=${MOODLE_DB_TYPE}
      - MOODLE_DB_HOST=${MOODLE_DB_HOST}
      - MOODLE_DB_NAME=${MYSQL_USER}
      - MOODLE_DB_USER=${MYSQL_USER}
      - MOODLE_DB_PASS=${MYSQL_PASSWORD}
      - MOODLE_URL=${MOODLE_URL}
      - MOODLE_DATAROOT=${MOODLE_DATAROOT-/var/local/moodledata}
      - MOODLE_DIRECTORYPERMISSIONS=${MOODLE_DIRECTORYPERMISSIONS-0754}
      - MOODLE_SSLPROXY=${MOODLE_SSLPROXY}
      - MOODLE_REVERSEPROXY=${MOODLE_REVERSEPROXY}
    restart: unless-stopped
    ports:
      - 127.0.0.1:${MOODLE_PORT-8080}:80
    volumes:
      - ./volumes/moodle:/var/www/html
      - ./volumes/moodledata:/var/local/moodledata
    depends_on:
      - db
